# Use debian stable as the base image.
FROM debian:stable

# Build argument defining the maximum heap size for gpt.
ARG MAX_HEAP_SIZE=4G

## Install wget.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get update -y \
&& apt-get --no-install-recommends install -y wget

# Get & setup the SNAP toolbox. Maximum heap size is set to 4GB.
RUN wget http://step.esa.int/downloads/7.0/installers/esa-snap_sentinel_unix_7_0.sh \
&& chmod 700 esa-snap_sentinel_unix_7_0.sh \
&& ./esa-snap_sentinel_unix_7_0.sh -q \
&& ln -s /usr/local/snap/bin/gpt /usr/bin/gpt \
&& sed -i -e "s/-Xmx1G/-Xmx${MAX_HEAP_SIZE}/g" /usr/local/snap/bin/gpt.vmoptions

ARG LIBS_DIR=blocks/snap-polarimetric/libs

RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "deb [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && echo "deb-src [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends -t sid python3.7 python3-setuptools python3-pip build-essential ca-certificates python3-wheel python3-dev openjdk-8-jre-headless openjdk-8-jdk-headless

# Making sure JRE is installed before we jump into installing JDK.
#RUN apt-get install -y --no-install-recommends -t sid

RUN mkdir -p /interstellar/libs

COPY requirements/requirements_snap.txt /interstellar/libs/
WORKDIR /interstellar/libs
RUN pip3 install -r requirements_snap.txt
