FROM python:3.7

RUN apt-get update && apt-get -y install coda harp libhdf5-dev
RUN h5cc -showconfig

RUN mkdir -p /interstellar/libs
WORKDIR /interstellar/libs

COPY requirements/requirements.txt /interstellar/libs/
RUN pip install -r /interstellar/libs/requirements.txt
