# base image for our CircleCI terraform workflows

# based on 2020 long term support version of ubuntu
FROM ubuntu:20.04

# to make php installation non-interactive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -yq \
    curl \
    unzip \
    ruby-full \
    make \
    gcc \
    php \
    jq \
    git \
    wget \
    unzip \
    gnupg \
    gnupg2 \
    software-properties-common

# add google cloud deb repo
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

# add kubectl deb repo
RUN curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
RUN echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list

# add github repository
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
RUN apt-add-repository https://cli.github.com/packages

# install google cloud-sdk and kubectl
RUN apt-get update
RUN apt-get install -yq \
    apt-transport-https \
    ca-certificates \
    google-cloud-sdk \
    kubectl \
    gh

# install rake
RUN gem install rake

# install terraform
RUN curl https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip -O
RUN unzip terraform_0.12.29_linux_amd64.zip
RUN chmod +x terraform
RUN mv terraform /usr/local/bin/

# install bundler for gem installation
RUN gem install bundler

# cache possible gems
COPY gemfiles .
RUN bundler install

# install community terraform providers
RUN mkdir -p $HOME/.terraform.d/plugins/linux_amd64/
RUN wget https://github.com/russellcardullo/terraform-provider-pingdom/releases/download/v1.1.1/terraform-provider-pingdom_v1.1.1_linux_amd64_static -O $HOME/.terraform.d/plugins/linux_amd64/terraform-provider-pingdom_v1.1.1
RUN chmod +x $HOME/.terraform.d/plugins/linux_amd64/terraform-provider-pingdom_v1.1.1
RUN wget https://github.com/gavinbunney/terraform-provider-kubectl/releases/download/v1.5.1/terraform-provider-kubectl-linux-amd64 -O $HOME/.terraform.d/plugins/linux_amd64/terraform-provider-kubectl
RUN chmod +x $HOME/.terraform.d/plugins/linux_amd64/terraform-provider-kubectl
