# Use python stretch (debian) stable as the base image.
FROM python:3.8.6

# Build argument defining the maximum heap size for gpt.
ARG MAX_HEAP_SIZE=4G

## Install wget.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get update -y \
&& apt-get upgrade -y \
&& apt-get --no-install-recommends install -y wget

# Get & setup the SNAP toolbox. Maximum heap size is set to 4GB.
RUN wget http://step.esa.int/downloads/7.0/installers/esa-snap_sentinel_unix_7_0.sh \
&& chmod 700 esa-snap_sentinel_unix_7_0.sh \
&& ./esa-snap_sentinel_unix_7_0.sh -q \
&& ln -s /usr/local/snap/bin/gpt /usr/bin/gpt \
&& sed -i -e "s/-Xmx1G/-Xmx${MAX_HEAP_SIZE}/g" /usr/local/snap/bin/gpt.vmoptions

ARG LIBS_DIR=blocks/snap-polarimetric/libs

# gcc-8-base dependency is inspired by https://unix.stackexchange.com/a/592703
RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "deb [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && echo "deb-src [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends -t sid build-essential gcc-8-base ca-certificates openjdk-8-jre-headless openjdk-8-jdk-headless libgeos-dev

# Making sure JRE is installed before we jump into installing JDK.
#RUN apt-get install -y --no-install-recommends -t sid

RUN mkdir -p /up42/libs

COPY requirements/requirements_snap.txt /up42/libs/
WORKDIR /up42/libs
RUN pip3 install -r requirements_snap.txt
