FROM osgeo/gdal:ubuntu-small-latest

ARG PYTHON=python3.7

ENV LANG C.UTF-8

RUN apt-get update
RUN apt-get install apt-utils wget -y
RUN apt-get install software-properties-common -y

RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get install -y ${PYTHON}

RUN wget https://bootstrap.pypa.io/get-pip.py
RUN ${PYTHON} get-pip.py
RUN ln -sf /usr/bin/${PYTHON} /usr/local/bin/python3
RUN ln -sf /usr/local/bin/pip /usr/local/bin/pip3

RUN pip --no-cache-dir install --upgrade \
    pip \
    setuptools

RUN apt-get install python3.7-dev python3-dev python-dev -y
RUN apt-get install gcc -y
RUN ln -f $(which ${PYTHON}) /usr/local/bin/python
RUN pip install --upgrade --force-reinstall numpy

RUN mkdir -p /up42/libs
WORKDIR /up42/libs

COPY requirements/requirements.txt /up42/libs/
RUN pip install -r /up42/libs/requirements.txt
