FROM python:3.7

RUN apt-get update && apt-get -y install coda harp libhdf5-dev
RUN h5cc -showconfig

RUN mkdir -p /up42/libs
WORKDIR /up42/libs

COPY requirements/requirements.txt /up42/libs/
RUN pip install -r /up42/libs/requirements.txt
