# Use python stretch (debian) stable as the base image.
FROM python:3.7-stretch

# Build argument defining the maximum heap size for gpt.
ARG MAX_HEAP_SIZE=4G

## Install wget.
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get update -y \
&& apt-get upgrade -y \
&& apt-get --no-install-recommends install -y wget

# Get & setup the SNAP toolbox. Maximum heap size is set to 4GB.
RUN wget https://step.esa.int/downloads/8.0/installers/esa-snap_sentinel_unix_8_0.sh \
&& chmod 700 esa-snap_sentinel_unix_8_0.sh \
&& ./esa-snap_sentinel_unix_8_0.sh -q \
&& ln -s /usr/local/snap/bin/gpt /usr/bin/gpt \
&& sed -i -e "s/-Xmx1G/-Xmx${MAX_HEAP_SIZE}/g" /usr/local/snap/bin/gpt.vmoptions \
&& sed -i -e "s#DEM.srtm3GeoTiffDEM_HTTP = http://cgiar-csi-srtm.openterrain.org.s3.amazonaws.com/source/#DEM.srtm3GeoTiffDEM_HTTP = http://skywatch-auxdata.s3-us-west-2.amazonaws.com/dem/SRTM90/tiff/#g" /usr/local/snap/etc/snap.auxdata.properties

ARG LIBS_DIR=blocks/snap-polarimetric/libs

RUN export DEBIAN_FRONTEND=noninteractive \
    && echo "deb [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && echo "deb-src [trusted=yes] http://ftp.us.debian.org/debian sid main" >> /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends -t sid build-essential ca-certificates openjdk-8-jre-headless openjdk-8-jdk-headless libgeos-dev

# Making sure JRE is installed before we jump into installing JDK.
#RUN apt-get install -y --no-install-recommends -t sid

RUN mkdir -p /up42/libs

COPY requirements/requirements_snap.txt /up42/libs/
WORKDIR /up42/libs
RUN pip3 install -r requirements_snap.txt
